name: Publish to Cargo

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'publish'

    steps:
      - uses: actions/checkout@master
        name: "checkout"
        with:
          fetch-depth: 0

      - uses: tu6ge/publish-action@v0.4.5
        name: "publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
